package ENUM;

public enum PermissionKey {
    // Nhân viên
    EMPLOYEE_INSERT, EMPLOYEE_DELETE, EMPLOYEE_UPDATE,

    // Khách hàng
    CUSTOMER_INSERT, CUSTOMER_DELETE, CUSTOMER_UPDATE,

    // Sản phẩm
    PRODUCT_INSERT, PRODUCT_DELETE, PRODUCT_UPDATE,

    // Nhà cung cấp
    SUPPLIER_INSERT, SUPPLIER_DELETE, SUPPLIER_UPDATE,

    // Bán hàng & Nhập hàng
    ORDER_CREATE, ORDER_VIEW,
    IMPORT_CREATE, IMPORT_VIEW,

    // Danh mục & Khuyến mãi
    CATEGORY_INSERT, CATEGORY_DELETE, CATEGORY_UPDATE,
    PROMOTION_INSERT, PROMOTION_DELETE, PROMOTION_UPDATE,

    // Hệ thống & Tài khoản
    ROLE_INSERT, ROLE_DELETE, ROLE_UPDATE, PERMISSION_UPDATE,
    ACCOUNT_INSERT, ACCOUNT_DELETE, ACCOUNT_UPDATE,

    // Thống kê
    STATISTICS_VIEW;
}