package ENUM;

public enum ServiceAccessCode {
    ROLE_PERMISSION_SERVICE,
    INVOICE_DETAILINVOICE_SERVICE,
    IMPORT_DETAILIMPORT_SERVICE,
    LOGIN_SERVICE,
    DISCOUNT_DETAILDISCOUNT_SERVICE,
    REGISTER_SERVICE,
}
